services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: caeser_user
      POSTGRES_PASSWORD: caeser_pass
      POSTGRES_DB: caeser
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U caeser_user -d caeser"]
      interval: 30s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  caeser-api:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  caeser-frontend:
    image: python:3.11-slim
    working_dir: /app
    command: >
      sh -c "
        pip install streamlit requests python-dotenv plotly openpyxl reportlab &&
        streamlit run frontend/src/main.py --server.port=8501 --server.address=0.0.0.0
      "
    ports:
      - "8501:8501"
    env_file: .env
    depends_on:
      - caeser-api
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  pgdata: