from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4c0ff554c6e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = sa.inspect(op.get_bind())
    tables = inspector.get_table_names()

    if 'cultural_insights' not in tables:
        op.create_table('cultural_insights',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('location', sa.Text(), nullable=False),
        sa.Column('category', sa.Text(), nullable=False),
        sa.Column('data', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('idx_insights', 'cultural_insights', ['location', 'category'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_insights', table_name='cultural_insights')
    op.drop_table('cultural_insights')
    # ### end Alembic commands ###